export const skipKeys = new Set([
  "coalition",
  "weapon1_type",
  "weapon2_type",
  "weapon3_type",
]);

export const closenessSets = {
  autonomy: [
    "N/A",
    "60",
    "75",
    "90",
    "105",
    "120",
    "135",
    "150",
    "160",
    "165",
    "180",
    "195",
    "200",
    "230",
    "240",
    "250",
    "270",
    "280",
    "300",
    "320",
    "350",
    "360",
    "370",
    "390",
    "400",
    "410",
    "420",
    "425",
    "430",
    "435",
    "440",
    "450",
    "460",
    "470",
    "480",
    "500",
    "510",
    "520",
    "530",
    "540",
    "550",
    "560",
    "570",
    "575",
    "600",
    "630",
    "640",
    "650",
    "660",
    "680",
    "685",
    "700",
    "710",
    "720",
    "750",
    "785",
    "790",
    "800",
    "850",
    "900",
    "930",
    "950",
    "1000",
    "1100",
    "1200",
    "1600",
    "2000",
  ],
  strength: ["2", "3", "4", "5", "6", "8", "10", "15", "100"],
  optics: ["Bad", "Poor", "Medium", "Good", "Very good", "Exceptional"],
  stealth: ["Poor", "Medium", "Good", "Very good", "Exceptional"],
  size: ["Very small", "Small", "Medium", "Big", "Very big"],
  speed: [
    "23",
    "30",
    "35",
    "38",
    "40",
    "45",
    "50",
    "55",
    "60",
    "65",
    "70",
    "75",
    "80",
    "85",
    "90",
    "95",
    "100",
    "105",
    "110",
    "120",
    "180",
    "185",
    "200",
    "205",
    "210",
    "220",
    "240",
    "250",
    "260",
    "270",
    "275",
    "280",
    "285",
    "290",
    "300",
    "310",
    "315",
    "320",
    "330",
    "350",
    "500",
    "600",
    "750",
    "900",
    "1000",
    "1100",
  ],
};

export const catTooltips = {
  name: "Never considered close",
  price: "Close if within five for price <= 50, else within ten",
  year: "Close if within a year",
  country: "Close if sharing coalition",
  tab: "Never considered close",
  speed:
    "Close if adjacent to the right result in a sorted list of possible speeds for units",
  autonomy:
    "Close if adjacent to the right result in a sorted list of possible autonomies for units",
  strength:
    "Close if adjacent to the right result in a sorted list of possible strenghts for units",
  optics:
    "Close if adjacent to the right result in a sorted list of possible optics for units",
  stealth:
    "Close if adjacent to the right result in a sorted list of possible stealths for units",
  size: "Close if adjacent to the right result in a sorted list of possible sizes for units",
  weapon1: "Close if weapon of same type",
  weapon2: "Close if weapon of same type",
  weapon3: "Close if weapon of same type",
  categories: "Close if subset of right answer",
};

export const summaryVals = {
  price: ["?", "?"],
  year: ["?", "?"],
  country: ["?"],
  speed: ["?", "?"],
  autonomy: ["?", "?"],
  strength: ["?", "?"],
  optics: ["?", "?"],
  stealth: ["?", "?"],
  size: ["?", "?"],
  categories: [],
  weapon1: null,
  weapon2: null,
  weapon3: null,
};

export const ordinalCats = [
  "price",
  "year",
  "speed",
  "autonomy",
  "strength",
  "optics",
  "stealth",
  "size",
];

export const coalitionToCountry = {
  Commonwealth: ["United Kingdom", "Canada", "ANZAC"],
  NORAD: ["Canada", "United States"],
  Eurocorps: ["West Germany", "France"],
  LANDJUT: ["West Germany", "Denmark"],
  "Dutch-German Corps": ["West Germany", "The Netherlands"],
  Scandinavia: ["Norway", "Denmark", "Sweden"],
  "Blue Dragons": ["South Korea"],
  "Eastern Bloc": ["Poland", "Czechoslavakia"],
  "Baltic Front": ["Poland", "Finland"],
  Entente: ["Czechoslavakia", "Yugoslavia"],
  "Red Dragons": ["China", "North Korea"],
};

export const firstTarget = {
  "2025-07-09": { idx: 337, name: "Eland 60", date: "2025-07-09" },
};
export const firstDate = new Date(2025, 7, 9);
